# Generated by Django 4.2.7 on 2023-12-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postmodel_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='img_name',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
